- src/jquery.multiselect.js
- tests/unit/index.htm
Unit tests are now up to date and passing.
Index.html is referencing current libraries rather than base revisions. As per: http://stackoverflow.com/questions/12608242/latest-jquery-version-on-googles-cdn
Using the base revisions to get the latest library versions is no longer supported so we need to manually update these to the latest as they come along.
I set the title property to a sanitized version of the option elements text content if no title was initially provided. This is in line with the assertions in the unit tests.
> Updated Unit Tests

- src/jquery.multiselect.js
Custom menu width can be used in case of lack of space for select, and long text in options.
Usage: $('select').multiselect({ minWidth: 100, menuWidth:250 });
> Added option for setting custom menu width

- src/jquery.multiselect.filter.js
- src/jquery.multiselect.js
- MultiSelect: Form events not being unbound on destroy.
- Filter: Document events not being unbound on destroy.
- Filter: Removed circular reference that prevented garbage collection.
Have not updated minified javascript!
> Fix memory leaks.

- i18n/jquery.multiselect.filter.hu.js
- i18n/jquery.multiselect.hu.js
Two translation files are added to i18n directory for Hungarian language.
> Hungarian translation

- src/jquery.multiselect.js
- tests/unit/options.js
The default close icon is very close to the clear icon, which can be confusing.  I've added an option to set the close icon to something else (I'm using ui-icon-search).
> make close icon configurable

- src/jquery.multiselect.js
Swapped out deprecated $().delegate() API calls for equivalent $().on() API calls.
> Eliminate deprecated jQuery API calls

- src/jquery.multiselect.js
- tests/unit/core.js
- tests/unit/options.js
_(This is a re-do of #719 on the new version3 branch.)_
* Update jquery.multiselect.js
Eliminate the need for the multiple option by instead relying on the multiple attribute of the underlying native select element.
* Update core.js
* Update options.js
Update tests due to elimination of using multiple option in favor of using multiple attribute of underlying native select.
> Multiple option elimination (redo of #719)

- src/jquery.multiselect.filter.js
- src/jquery.multiselect.js
- tests/unit/methods.js
- tests/unit/options.js
Mostly a variable re-naming and commenting update.
1. Updated version number to 3.0.0 in code heading
2. Updated jQuery version dependency to 1.7+ due to deprecation of `$().delegate & $().bind()`, and use of `$().on()` instead
3. Detailed comments for each option to explain the permitted value types and the intended use of the option.
4. Switch default for selectedText option to be `# of # selected` to ensure that developers know that this form is supported.
5. Follow the popular convention of prefixing variable names of jQuery objects with a dollar sign for more clarity.
6. Use local variables for properties fetched more than once.
7. Ditch use of `$().bind()` in favor of `$().on()`, as bind is deprecated.
Unit tests have been updated.
> $variable naming & comments

- jquery.multiselect.css
- src/jquery.multiselect.filter.js
- src/jquery.multiselect.js
- tests/unit/core.js
- tests/unit/options.js
1. Add htmlButtonText option
2. Add htmlOptionText option - Addresses #696
3. Use more local variables instead of frequently referencing widget properties/options.
4. Use document.createElement() to more quickly create new DOM elements.  Addresses #717 comment 1 and #724.
5. Eliminate use of href="#" in header links.  Add cursor: pointer to jquery.multiselect.css for these links.
6. Move insertions to end of _create to limit browser reflowing lags.
7. Use more ternary operators to eliminate if/then's where it makes sense.
8. Create _updateCache() internal function... called from multiple places.
9. Ditch use of $.isFunction.  A simple typeof can be reliably used instead.
10. Add check in update() to reposition menu if button height has changed from saved value and the menu is open. …
> Improve performance and fix issues

- src/jquery.multiselect.filter.js
- src/jquery.multiselect.js
- tests/unit/events.js
- tests/unit/filter.js
Handles #733 
Replaces the separate _toggleChecked function code in multiselect.filter.js with instead using a parameter that changes the context for _toggleChecked in multiselect.js .
Also, a few housekeeping updates.
_Note: The events.js file that I pulled has tabs in it. What I am pushing back has spaces instead. (consider this fair warning...)
> Eliminate replacement _toggleChecked code in multiselect.filter.js

- src/jquery.multiselect.js
- tests/unit/options.js
Addresses #717, Closes #737 and PR #584.
1. Fix/finish maxSelected functionality.
2. Fix related test.
3. Fix namespace period issue.
4. Add new event triggers requested by open PR #584
> Max selected and misc updates

- css/jquery.multiselect.css
- src/jquery.multiselect.js
Addresses #739
1.  Add zIndex option to allow overriding menu z-index for edge use cases.
2.  Add logic to assign a reasonable z-index if not appending to a jQuery UI Dialog.  (e.g., appending to document.body instead)
3.  Go back to setting the menu position on every open in case the button has been moved (e.g. container dialog moved) from the last open.
4.  Close the menu if the mouse cursor is outside the menu and the mouse wheel is turned.   This fixes a scrolling issue that made the menu look detached from the button when the mouse wheel was turned.
5.  Add _allowInteraction support for jQuery modal dialogs to prevent interaction issues when appending to document body to prevent menu truncation.
Note these changes do not directly fix the menu truncation issue.  However, they do make …
> Menu clipping

- src/jquery.multiselect.filter.js
- src/jquery.multiselect.js
1.  Make filterRules a local variable.  (missed this before)
2.  Remove the unneeded multiselect() fxn call to get the widget instance--just use data() by itself.  (forgot to attempt this before)
3.  Save additional class names in variables that can be obfuscated away.
4.  Use ui-multiselect-grouplabel class name instead of finding the anchor tag directly.
5.  Decrease unneeded jQuery fxn calls w/ use of classList methods.
No feature changes.  All unit tests pass.
Fixes #195
Fixes #551
This fixes undesired scrolling issues caused by focusing an element that is only partially visible.
All unit tests pass.
> Filter Code Refactor & Fix Scroll on Focus Issues

- src/jquery.multiselect.filter.js
Fix same bug as was reported in issue #154.
This original bug was fixed in commit 47854a0 (fix for hiding/showing optgroups when optionlist is hidden) but reintroduced in commit a9fcf40 (Option Groups are now ul elements instead of additional list items. )
Description of problem:
When having optgroups and using filtering in the multiselect, the optgroups get hidden after calling refresh. This problem does not occur when no optgroups are used.
On checking the visibility of the items inside the optgroups the wrong check (:visible selector) was used; the items will not be visible yet. However, they are not hidden on purpose with display:none, so checking on that css is the better way of checking for 'visibility'.
> Prevent unwanted hiding of optgroups after refresh

- css/jquery.multiselect.css
- demos/animations.htm
- src/jquery.multiselect.js
Closes #758.
Aligns animation options with current .show() & .hide() signatures.
The current array object support for the openEffect and closeEffect options is maintained.
It does align with the current `.show( effect [, options ] [, duration ] [, complete ] )` signature (or for `hide`), for the case of the `[, options ]` and `[, complete ]` parameters being omitted, since the two array parameters are supplied for the effect and duration parameters.
However, support for a plain object of animation settings for the openEffect and closeEffect options is also now supported.  This aligns with the current `.show( options )` signature (or for `hide`), and allows the easing to be specified in the object.
> Update animation support

- src/jquery.multiselect.js
Fix #770 
Added a parameter to allow _traversing() to allow scrolling (unlock scroll position) on input focus when changing focus via keyboard traversing.
> Fix #770 - Scroll on Focus w/ _traverse()

- src/jquery.multiselect.js
Closes #777 
_(Provide use cases, code references, [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io), etc.)_
Position / set dimensions of menu before doing animation.
Add this.element.trigger('blur') to close()
Hide menu for animation effects.
Some animation effects (e.g. fade) require the menu to be hidden and shown w/ the effect to work properly.
For example, if the menu is already displayed, fade will make it hidden.
@SteveTheTechie 
This is your PR but rebased onto version 3. I'll merge this one.
> Fix #775 - Animation / positioning sequence

- src/jquery.multiselect.js
Native Select element could be initially hidden in the case of a dialog.
n/a
_(Provide use cases, code references, [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io), etc.)_
If the native select is initially hidden in the case of a dialog, the initial width determination will need to be done w/ $.outerWidth() instead of _getBCRWidth().
@mlh758
> Use $.outerWidth() for Native Select Element Width

- src/jquery.multiselect.js
Closes #795
_(Provide use cases, code references, [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io), etc.)_
- Switch to using offsetTop and offsetHeight in _setMenuHeight()
- Eliminate need for _getBCRHeight() and _jqHeightFix()
@mlh758
> Closes #795

- src/jquery.multiselect.js
This very small change prevents browsers from converting trailing newlines to spaces when using the selectedList option and the underlying select lacks closing &lt;/option&gt; tags.  Without this, it looks like there are extra spaces added to the untrained eye. (it is just the newlines that get converted)
-  Feature addition
-  Code refactoring / optimization
-  Test Addition
-  Demo Addition
-  i18n Addition
-  Other (explain below)
n/a
_(Provide use cases, code references, [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io), etc.)_   
The added .replace(/\n$/, '') just takes off the unnecessary ending newline that is part of the option text when no &lt;/option&gt; tags are used.
@mlh758
> Eliminate Trailing New Lines from Unterminated Option Text

- src/jquery.multiselect.js
n/a
_(Provide use cases, code references, [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io), etc.)_   
Switch default collapse/expand icons to minuses and pluses...   
These seem to be more intuitive than the triangle icons I originally came up with.
@mlh758
> Change default collapse/expand icons

- src/jquery.multiselect.js
This Pull Request is a bug fix
Check existing of $button inside _toggleDisabled function becase $button is undefined if listbox option is set to true.
> fix _toggleDisabled error this.$button is undefined when listbox option is set to true

- src/jquery.multiselect.js
As i describe in my issue, my menu gets placed in a strange random position.
I found out that the issue is with the jQuery `.position()` function, which for some reason gets confused on my setup.
Both the `left` and `top` properties are wrong - if I base it on the `.offset()` functionality, then it works fine
I have a feeling that this fix can have some pretty crazy consequences - and it really surprises me that noone else seems to have this issue..
https://github.com/ehynds/jquery-ui-multiselect-widget/issues/837
>"Took 821 ms to run 334 tests. 334 passed, 0 failed."
> ISSUE 837: Use jquery offset instead of .position().

- .gitignore
- src/jquery.multiselect.js
"class"is a reserved word in javascript.  See [this reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/class).  yuicompressor flags its use as a syntax error as described in #846.
This patch avoids using the reserved word by making the references using array reference syntax instead.
Fixes #846
> Fix compile errors due to reserved word "class"

- src/jquery.multiselect.filter.js
- src/jquery.multiselect.js
This pull request allows the groupColumns boolean to be used outside of the optgroup tagname to general list items, and it adds a groupColumnsWidth option to allow for nicer alignment of elements in the respective rows.  This could be done using flex, but for now, width should be fine.
Closes #854 
- [ x ] Tests Ran and 0 Failing
> Increase use of groupColumns and add groupColumnsWidth option

- src/jquery.multiselect.js
This one mostly passes the unit test.  The new unit test for width has one issue with a difference in width, not sure if that is a problem with the test though.
Allows the specification of the column width for columnGroups and allows columnGroups to be used for the generalized multiselect.
Closes #854
- [ x ] Tests Ran and 0 Failing (actually one is failing, though might be the new filter test)
- [ n/a ] Tests Added/Updated
- [ n/a ] Impacted Demos Updated
- [ n/a ] Impacted i18n Code Updated
> Re-implement groupColumnsWidth

- src/jquery.multiselect.js
- tests/unit/options.js
This allows users to send an object in the header option with a custom name for available linkInfo.
> Option to add custom text for default linkInfo(header)

- src/jquery.multiselect.js
I'm trying to migrate to jQuery 3.6.0 and found out warnings as follows:
We can simply replace `focus()` with `trigger('focus')` to eliminate these warnings.
N/A
Honestly, I don't know how to add tests, but the changes are quite straightforward and they work well in my project.
> Removed focus event shorthand invocation.
